### ISSUE TITLE
Example. Out of bounds in CollisionSystem::collect

### ISSUE THREAD

**Issue by c0ffeeartc** [alecthomas/entityx#100]
Example crashes in debug mode inside CollisionSystem::collect.
```
        unsigned int slots[4] = {
          left + top * size.x,
          right + top * size.x,
          left  + bottom * size.x,
          right + bottom * size.x,
        };
        grid[slots[0]].push_back(candidate);
        if (slots[0] != slots[1]) grid[slots[1]].push_back(candidate);
        if (slots[1] != slots[2]) grid[slots[2]].push_back(candidate);
        if (slots[2] != slots[3]) grid[slots[3]].push_back(candidate);
```
Bounds check removes crash. Searching root cause solution.

**Comment by alecthomas** [comment]
I'm unable to replicate. What display resolution/compiler/system?

**Comment by c0ffeeartc** [comment]
```
gcc (GCC) 4.9.2 20150304 (prerelease)
Linux za 4.0.4-1-ARCH #1 SMP PREEMPT Mon May 18 06:43:19 CEST 2015 x86_64 GNU/Linux

screen resolution: 1920x1080
```

After more thorough check, it crashes only if stepped through gdb(cgdb). I use i3 window manager and when stepped - app starts using halfscreen/fullscreen(hard to tell), I move it to another workspace(fullscreen), and work in debugger on different workspace, so this might be an issue.

Anyways, when not in debugger, `cout` debug logs never output a problem. So it must be my setup, sorry bothering.
