### ISSUE TITLE
System_test.cc vs2013: internal compiler error

### ISSUE THREAD

**Issue by jbmcgee** [alecthomas/entityx#101]
Building master with VS 2013 Community Edition
I get:
```
errorC1001: An internal error has occurred in the compiler.
```
in system_test.cc at line 67:
```
entity.unpack<Counter>(counter);
```

**Comment by alecthomas** [comment]
Have you installed all of the CTP's?

**Comment by jbmcgee** [comment]
Yest, I've installed up to Update 5.

**Comment by alecthomas** [comment]
I have EntityX hooked up to the AppVeyor CI, and it passes, so it's not a (general) issue with EntityX and VS. If I had to guess, I'd say it's some issue with your installation, but I don't know Windows well enough to help. Sorry :(
