### ISSUE TITLE
Pass all managers to System::configure()

### ISSUE THREAD

**Issue by c0ffeeartc** [alecthomas/entityx#104]
`System::configure()` seems a good place to pass all managers.
Saves hassle on passing them through constructor( in case of storing pointer it's changing 1 file `FooSystem.cpp`, versus 3 `BarEntityX.cpp`, `FooSystem.h `, `FooSystem.cpp`), it's called once right after construction, why not use it?

**Comment by alecthomas** [comment]
Not a bad idea. I'm not 100% sure why I didn't do that originally, as it seems like a pretty good location to spawn initial entities, etc.
