### ISSUE TITLE
Update README to include latest LTS instructions

### ISSUE THREAD

**Issue by unerize** [alecthomas/entityx#106]
the readme should probably get updated especially the part on ubuntu/linux its still from version 12.04.
Also would like more examples could help with that if i finish a game :P good work on this btw

**Comment by alecthomas** [comment]
I don't have any 14.x installs around, but if you send a PR I'll merge it.

More examples are always welcome too.

**Comment by unerize** [comment]
does entityx have any dependencies? i tried compiling it again to see what the process was, but maybe i had the dependencies already installed. if it doesn't have any dependencies you can just make it with cmake and build it with your favourite compiler

**Comment by alecthomas** [comment]
No it does not have any dependencies.
