### ISSUE TITLE
[Question] Update rountines running simultaneously?

### ISSUE THREAD

**Issue by Fighter19** [alecthomas/entityx#108]
Hey there, I'm trying to use EntityX, to develop a little cross-platform game.
Everything works fine at the moment. The problem is just, when I use update (from the entity to which different systems are assigned), the systems seem to run updates simultaneously (like in multiple threads). I wanted to ask, if that's the real case, or if I'm just imagining that. (I use a system which renders, and a system which displays, however the one which displays seems to pass the picture before the system which renders is finished). And if that's my correct assumption I wanted to ask, if there is a way to avoid that. Do I need to use events to realize that?

**Comment by alecthomas** [comment]
Hi there,

No, EntityX does not execute anything in parallel. I'm guessing there's a slight bug in your code which is causing that behaviour :(

All the best,
Alec

**Comment by alecthomas** [comment]
PS. If you want help debugging, feel free to send a mail to the mailing list.

**Comment by Fighter19** [comment]
Thank you! I at least know where to search now, I guess it might be some memory related thing.
