### ISSUE TITLE
Entity.h delete definition warning

### ISSUE THREAD

**Issue by facehead1992** [alecthomas/entityx#109]
The 602nd line of "Entity.h"...

<code>
new(pool->get(id.index())) C(std::forward<Args>(args) ...);
</code>

...creates the following warning from the moment I create a project with EntityX.

Warning	C4291	'void *operator new(size_t,void *) throw()': no matching operator delete found; memory will not be freed if initialization throws an exception

Pretty sure a delete with the same parameters needs to be added, but since I'm not sure about the implementation details, I don't wanna just add a random one for fear of screwing something up. Figured I'd notify someone.

**Comment by alecthomas** [comment]
Can you try adding `::` in front of `new`:

```c++
::new(pool->get(id.index())) C(std::forward<Args>(args) ...);
```

**Comment by facehead1992** [comment]
Yes, that removed the warning. Thanks.

I've also had two "receive" functions collected for each call of "emit", regardless of which event object is emitted or which receiving system retrieves the event. I've double checked our code and haven't found anything, but seeing as how that's pretty major problem and no one has posted about that until now, I suspect it must be a problem on my end...
