### ISSUE TITLE
Warning generated by CMP0054, when cmake version >= 3.1

### ISSUE THREAD

**Issue by PHEN-** [alecthomas/entityx#113]
I'm currently using CMake 3.4.1 (on Windows if that matters).

I'm getting the following warnings:

```
EntityX version 1.1.2
CMake Warning (dev) at extinclude/entityx-repo/CMakeLists.txt:28 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
This warning is for project developers.  Use -Wno-dev to suppress it.
```

I don't think we mean to deference varaibles "Clang" or "MSVC" or "GNU" in those comparisons in there, so we can likely set the policy to NEW to get rid of this warning.

See also:

https://cmake.org/cmake/help/v3.1/policy/CMP0054.html

**Comment by alecthomas** [comment]
The linked policy doesn't make it clear why this is an issue in this case at all, but [this](https://cmake.org/pipermail/cmake-developers/2015-June/025421.html) mailing list post does.

I think the final solution would be better, ie. just remove the quotes:

```
if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
```

**Comment by PHEN-** [comment]
With #118 merged in, I believe we can close this.

**Comment by alecthomas** [comment]
👍
