### ISSUE TITLE
uint64_t': ambiguous symbol error in Benchmarks_test.cc under MSVC 2015

### ISSUE THREAD

**Issue by dendryte** [alecthomas/entityx#122]
Error	C2872	'uint64_t': ambiguous symbol	benchmarks_test	entityx\entityx\Benchmarks_test.cc	51	
this error also appears for lines 54, 61 and 63

Manually adding an include to stdint.h doesn't seem to fix it.

**Comment by PHEN-** [comment]
I've reproduced and found the ambiguous symbol error:

```
2>C:\Users\Stephen\OneDrive\Projects\github\entityx\entityx\Benchmarks_test.cc(47): error C2872: 'uint64_t': ambiguous symbol
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h(24): note: could be 'unsigned __int64 uint64_t'
2>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\stdint.h(24): note: or       'uint64_t'
2>  C:\Users\Stephen\OneDrive\Projects\github\entityx\entityx/Entity.h(40): note: or       'entityx::uint64_t'

```

It seems the Benchamark tests uses both the std:: and entityx:: namespaces. MSVC can't decide dispite the `using std::uint64_t;` in the benchmark_test.cc.

It might be a compiler difference between GCC and MSVC? Very curious why the `using std;:uint64_t` didn't work.
 
A workaround is to remove `using namespace std` and `using namespace entityx`, and add this in:

```
using std::uint64_t;
using std::cout;
using std::endl;
using std::vector;

using entityx::Receiver;
using entityx::Component;
using entityx::ComponentHandle;
using entityx::EntityCreatedEvent;
using entityx::EntityDestroyedEvent;
using entityx::EventManager;
using entityx::EntityManager;
using entityx::Entity;
```

**Comment by PHEN-** [comment]
Clang 3.5 also reports this a an ambiguous use also.

**Comment by alecthomas** [comment]
Is that the same MSVC version as the CI? CTP6? https://ci.appveyor.com/project/alecthomas/entityx/branch/master

Because it works fine. That said, if that's the only issue I'd happily accept a patch.

**Comment by PHEN-** [comment]
>Is that the same MSVC version as the CI? CTP6?

I'm running a slightly older patch. 

```
$ cl.exe
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.23026 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
```

> https://ci.appveyor.com/project/alecthomas/entityx/branch/master

It doesn't look like the benchmarks are built on appveyor. Perhaps add a -DENTIYIX_BUILD_BUT_DON'T_RUN benchmark target?
