### ISSUE TITLE
Entity::assign_from_copy(const C &component) weirdness

### ISSUE THREAD

**Issue by zackthehuman** [alecthomas/entityx#124]
I'm trying to write an `Entity` cloning function and I'm leveraging `assign_from_copy` to copy each component from a source to a new `Entity`. I noticed that it's possible to call `assign_from_copy` and provide a `ComponentHandle<C>` rather than an instance of `C`. To illustrate:

    entityx::Entity cloneEntity(entityx::EntityManager & entities, entityx::Entity & source) {
        auto clone = entities.create();

        if(source.has_component<Foo>()) {
            std::cout << "Cloning Foo..." << std::endl;
            clone.assign_from_copy(source.component<Foo>());
        }

        if(source.has_component<Bar>()) {
            std::cout << "Cloning Bar..." << std::endl;
            clone.assign_from_copy(source.component<Bar>());
        }

        return clone;
    }

This code compiles and runs, however, it doesn't work correctly. The component masks do not match after the cloning is complete. The reason for this is that it's not actually copying the component (the copy constructor is not called), but rather the handle itself.

It works correctly when I actually copy the components:

    entityx::Entity cloneEntity(entityx::EntityManager & entities, entityx::Entity & source) {
        auto clone = entities.create();

        if(source.has_component<Foo>()) {
            std::cout << "Cloning Foo..." << std::endl;
            clone.assign_from_copy<Foo>(*(source.component<Foo>().get()));
        }

        if(source.has_component<Bar>()) {
            std::cout << "Cloning Bar..." << std::endl;
            clone.assign_from_copy<Bar>(*(source.component<Bar>().get()));
        }

        return clone;
    }

I feel like this is an error that could either be a) prevented by causing a compilation error, or b) overload the method to accept a `ComponentHandle<C>` that grabs the underlaying `C` instance.

Thoughts?

**Comment by alecthomas** [comment]
This is basically creating a new component. The same could occur with 'get<C>()'.

It might be a good idea to have a static assert to prevent this though.

**Comment by alecthomas** [comment]
I'm not 100% sure about the compatibility of `static_assert` and whether the required SFINAE constructs would be supported be the same set of compilers that EntityX currently works with. For such a corner case, I think it's probably better not to add this.

**Comment by zackthehuman** [comment]
Yeah, I agree it's an edge case but it seems pretty easy to accidentally fall in to. If I come up with something that works and is supported by the same set of compilers we could have another discussion later.
