### ISSUE TITLE
Perfomance Comparison

### ISSUE THREAD

**Issue by XBog** [alecthomas/entityx#125]
just found this nice blog.
[Entity component Systems](https://tilemapkit.com/2015/10/entity-component-systems-compared-benchmarked-entityx-anax-artemis/)

![entity system chart](http://tilemapkit.com/tkwp/wp-content/uploads/Screen-Shot-2015-10-21-at-17.16.04.png)

Didn't test it myself. But if it's true, can we do something about it? :)

**Comment by alecthomas** [comment]
It is definitely not true, and you can test it for yourself with the [example code](https://github.com/alecthomas/entityx/blob/master/examples/example.cc) that EntityX includes. On my system the example pushes about 25K entites per frame, at around 250fps, so in the ballpark of 6M entities per second, including the actual render time and all the other processing.

I actually wrote a comment on the blog, but for some reason the blog only shows comments in [http](http://tilemapkit.com/2015/10/entity-component-systems-compared-benchmarked-entityx-anax-artemis/), not https. Here's what I wrote:

> I'm the author of EntityX, and it can certainly handle more than 100 entities, so I'm pretty surprised by the benchmark results. There's an example included in the EntityX source that processes around 20K entities per frame, and on my laptop gets > 200fps. You can run that in release mode with:
>
>    mkdir build && cd build && cmake -DENTITYX_RUN_BENCHMARKS=0 -DENTITYX_BUILD_TESTING=0 -DCMAKE_BUILD_TYPE=RelWithDebugInfo .. && make install
>    cd ../examples && c++ -L/usr/local/lib -I/usr/local/include -I.. -O3 -std=c++11 -DNDEBUG -Wall -lsfml-system -lsfml-window -lsfml-graphics -lentityx example.cc -o example && ./example
>
>I checked out the Xcode project for the benchmarks, and it seems that they are running in Debug mode. As EntityX includes a lot of assertions and checks when running in debug mode, it is definitely going to be slow. So this could be the main issue.

**Comment by sansumbrella** [comment]
Seems weird. I have never had issues with the performance of large numbers of entities in entityx (and have used tens of thousands of entities in projects).

**Comment by alecthomas** [comment]
I sent a [PR](https://github.com/LearnCocos2D/LearnCocos2D/pull/1) enabling release mode builds of the tests. This fixed the "issue" for me.

**Comment by XBog** [comment]
sounds good! :) thx

**Comment by romualdvilletet** [comment]
I posted my results on the facebook post about this blog article.
https://www.facebook.com/tilemapkit/posts/1098652236833502?comment_id=1148939951804730&comment_tracking=%7B%22tn%22%3A%22R%22%7D
