### ISSUE TITLE
~EntityManager() depends on having a valid EventManager

### ISSUE THREAD

**Issue by PHEN-** [alecthomas/entityx#127]
I ran into a slight usage issue issue with the following `App`:

```
struct App {
   App() : em(ev) {}

    EventManager ev;
    EntityManager em;
 }
 
 int main() {
    App a;
    a.em.create();
    return 0;
 }
```

What happens here is:

`~App()` is called
`~EventManager()` gets called, all signal handlers get destructed.
`~EntityManager()` calls `EntityManager::reset()`, which emits `EntityDestroyedEvent`

This caused a SEGFAULT in a weird spot during  EntityManager::emit<entityx::EntityDestroyedEvent, entityx::Entity>(entityx::Entity&&).

![backtrace of crash](https://cloud.githubusercontent.com/assets/1310292/12669250/e33f2e02-c613-11e5-92e3-72357d4d4c92.png)

Possible solution (not sure whats best) : 
 - Have `EntityManager` hold a share_ptr to `EventManager`.
 - Add a `destroy_no_events(..)` or `silent_destroy()` for use cases of destroying a entity without a valid `EventManager`.
 - Have users rewrite `App` such that `~EventManager()` comes after `~EntityManager()`.

**Comment by PHEN-** [comment]
As another note: The app is valid when complied on windows with MSVC15 and doesn't segfault on exit.

I'm curious as to why that is, but that's a bit off topic :).

**Comment by alecthomas** [comment]
According to [this](http://stackoverflow.com/a/2254306/7980) post, members should be constructed in the order they appear, and destructed in reverse order. If that is not the case, it seems that this is a compiler bug.

**Comment by PHEN-** [comment]
Ah. I was trying to dig for that. Awesome. I'm fine with closing this issue then since the standard recognizes it that way. 

Sounds like a MSVC bug then,  or me just being lucky that the Signal was still valid after deconstruction of the event manager.

Closing issue.
