### ISSUE TITLE
Can support for excluding entities with a specific component be added to EntityX?

### ISSUE THREAD

**Issue by heretique** [alecthomas/entityx#128]
Hi,

I think the ability to exclude entities from a system, based on a given component can also be powerful and could help a lot. I saw anax has it and I also implemented one in my own [AtlasECS ](https://github.com/heretique/AtlasECS) entity system for Unity. I found this feature to be of real use in different situations.
I took a look at EntityX's code but there's a lot of template "magic" there that is beyond my understanding :), hence the question.

**Comment by alecthomas** [comment]
This could be done, yes, but it might be just easier to do `if (e.has_component<C>) continue;` in the loop.

**Comment by heretique** [comment]
Indeed, but that means looping through all entities. The way entityx is implemented this is probably the best way to do it.
Thanks Alec
