### ISSUE TITLE
Finite State Machine for entity

### ISSUE THREAD

**Issue by igorkravchenko** [alecthomas/entityx#130]
Is it possible to add FSM for entity in similar way like [Richard Lord](https://github.com/richardlord) has done it in his [Ash](http://www.ashframework.org) framework?
He also wrote an [article](http://www.richardlord.net/blog/finite-state-machines-with-ash) for it.
I find this approach very handy.

**Comment by alecthomas** [comment]
It's an interesting approach, but it doesn't seem like it needs to be a core part of EntityX. If you do implement this, I'd happily add it to a contrib directory though, as it seems quite useful.

**Comment by FrankStain** [comment]
Frankly, FSM logics, described by Richard in article, looks too heavy for ECS.

Looking in this direction, any state of entity may be considered as template/prefab, which describe what components must be removed and what must be added.
So, simple state switching will be enough here. I mean, here we need only state switching and no other features of FSM, cuz all conditions, checks and transitions already must be managed by systems.
