### ISSUE TITLE
Suspicion on 'Copy-Paste' bug.

### ISSUE THREAD

**Issue by FrankStain** [alecthomas/entityx#136]
@alecthomas , hey! :)

Have a look at this code.
https://github.com/alecthomas/entityx/blob/master/entityx/Entity.h#L575

Currently i just interrested, why next line (Entity.h#L576) still uses `entity.index()` instead of already cached `index`. It looks like a 'copy-paste' bug, especially cuz all other code uses `index` variable.

**Comment by alecthomas** [comment]
I think you're right, though it won't cause any problems.

**Comment by FrankStain** [comment]
@alecthomas , my experience tell me fix this issue asap :)
So, would you like to fix it yourself? Or i can do so, if you not mind.

**Comment by alecthomas** [comment]
Go for it.
