### ISSUE TITLE
Entity iterators

### ISSUE THREAD

**Issue by OvermindDL1** [alecthomas/entityx#138]
It appears that iterators (or via .each(..lambda..);) are the main way to iterate over entities that have specific components.

Well the issue, beyond there being a hardcoded max of components allowed, is that this seems to iterate over every-single-entity, not just the ones requested, although it only returns just the ones requested.

Why this is an issue, in a little game that I keep porting from engine to library to engine to library is having a fairly major issue with this.  It has around a hundred thousand distinct objects/entities, up to a million, most are fairly tiny and can be represented with very little memory.  I was using SFML to handle the rendering including cached vertex arrays and all, but I was having a substantial speed issue so I ended up stripping out the entirety of SFML and just have entityx handling the game data, ended up stripping out all of the game data so it was just creating entities and the systems are just doing .each over the lists, which was reduced to a single system with a single .each over a single component type with a do-nothing function body, and this alone was taking over 30ms just to process with a half-million total entities but where only 40 entities have the components being searched for, and come to find out this iterator is iterating over every-single-entity, just only returning skipping most until it hits one that matches the internal bitset.

This little test game handles a lot of entities of various types, generally a few hundred component types when designed in an ECS library, but never had such an issue as this.  Usually an ECS library has something that is a cache of existing entities with given components, generally held within the component handler itself.  Some pseudo-code with scaffolding removed:
```cpp
struct HealthComponentTable {
    // Table is either an unordered_map, map, or vector internally based on component count, the key is an entityid, which is generally a low 32-bits of index reused with a high 32-bits being a counter to test validity of the handle.  Table has an internal dynamic bitset when it is using a vector to state which index is in-use, otherwise a map is self-defining
    Table<uint16> table_;
}

EntityID entity = context.createEntity();
context.setComponent<HealthComponentTable>(entity, 100);
std::cout << context.getComponent<HealthComponentTable>(entity);
```
And although I know this is a bit different from the entityx design it is curious why it touches any entities that have no need to be touched as most of the entities and their components are 'sleeping' with nothing to do the majority of the time, so they should not be taking such time...

A work-around for my testing is to listen to ComponentAddedEvent events and be certain never to iterate over the components instead but only use my cached entities, this gets the speed back to up an acceptable level, from over 500ms/frame to <4ms/frame, but still slower than expected compared to the above ECS design.

What is the way that entityx is supposed to be used as apparently doing .each() for the components is not the thing to do?

**Comment by alecthomas** [comment]
EntityX is not designed for large numbers of sparsely populated entities. This is deliberate, but may not be appropriate for use cases like yours. The experimental/compile_time branch has custom storage backends which are designed to be customisable for this purpose, but I haven't had time to clean it up and push it as EntityX v2.

Also see #135, #68, etc.

That said, unless you are building with optimisations on, and `-DNDEBUG`, you're incurring a significant overhead due to assertions.

**Comment by OvermindDL1** [comment]
It was a release build, just hitting a lot of entities.  A work-around might be use an Aspect style system using the events.  Would require no changing of existing code or functionality, just if people want to use the Aspects then they should not use the iterators.
