### ISSUE TITLE
2.0 Branch questions.

### ISSUE THREAD

**Issue by roig** [alecthomas/entityx#141]
As you can see in my last failed pull request, I'm trying to get the exporting as a DLL of this library, but before that I have some questions.

I saw that in the 2.0 branch you removed the event subsystem. Will the next release not have Events? (I vote yes for that, and removing simplesignals etc.. )

Can we update the 2.0 branch and define some milestones for it? I'm new to opensource working workflow, so I don't know exactly where we can define those things here in github.

I don't fully examined your code but, is there a reason to make this a compiled library instead of a template header only library?

(I have the dll exporting working but there is one test that fails, and is related to the event system)

**Comment by alecthomas** [comment]
Correct, there are no events as such in 2.0. There is a compile-time feature that can enable callbacks for similar functionality. 

The major remaining work is refactoring how storage backends work so that they're flexible enough for the majority of use cases.

2.0 is already header only.

**Comment by roig** [comment]
Uhmmm the last time I checked we had to compile the library and link it, now it's not that way?

**Comment by alecthomas** [comment]
I see where the confusion lies. I'm talking about the compile_time branch, which will become 2.0. The 2.0 branch is not the next version and should be removed.

**Comment by roig** [comment]
Ops! Yeah you are right!
So can we use compile_time branch for production?

**Comment by alecthomas** [comment]
Well, it is quite functional, so it can be used, but it's likely to change in a backwards incompatible way before it is released as 2.0. Your call.

**Comment by roig** [comment]
Thank you, I will switch there and if I see issues I will report it/fix it.

**Comment by roig** [comment]
Hello again Alecthomas, I'm trying the compile_time branch and I tried to port my project to this new version without success.

The main problem I'm facing with this new version is that the need of doing this:
(the include of all components depends on the GameEntityManager::Entity type)
```
EntityUtils.h :
 
 #include "Endavant/entityx/entityx/entityx.hh"
 #include "Endavant/game/components/Transform.hpp"
 namespace edv {
 	using GameComponents = entityx::Components<edv::components::Transform>;
 	using GameEntityManager = entityx::EntityX<GameComponents, entityx::ColumnStorage<GameComponents>>;
 	template <typename C> using GameComponent = GameEntityManager::Component<C>;
 	using GameEntity = GameEntityManager::Entity;
 } /* namespace edv */
```

My Transform component mantains the hierarchy of the Entities, so I have something like that:

```
 Transform.hpp
 #include "EntityUtils.h"

class Transform {
 public:
      ........
 	GameEntity getParent() const;
 	void setParent(const GameEntity &parent);
	const std::vector<GameEntity> & getChildren() const;
 	GameEntity getChild(const std::size_t position) const;
 private:
      ......
      GameEntity m_parent;
 	std::vector<GameEntity> m_children;
 };
```

As you can see there is a circular dependency that I can't broke. No matter what I tried.. I Always got a circular dependency.

Maybe I'm missing something? But I think that we should avoid doing this in the first place:

`using GameComponents = entityx::Components<edv::components::Transform>;`

**Comment by alecthomas** [comment]
> Maybe I'm missing something? But I think that we should avoid doing this in the first place:

It's fundamental to the compile-time approach unfortunately. It can not be avoided with this implementation.

A solution to both of these problems is to store the entity ID, not the Entity itself. All of the Entity operations are available as methods on the EntityManager.

This is part of the reason I haven't promoted this implementation to 2.x; there are some warts.

**Comment by roig** [comment]
Yesterday I tried your approach of storing the ids but it was the same, because in the end I had to pass somewhere my EM instance.. And for returning the components I can't predeclare anything because of template.

I will have to switch back to the old branch sadly. But at least we have some feedback of the new branch :p. If you change the implementation to avoid these problems I will try it with my project for sure, to get a "real world" use case.
Thank you!

**Comment by alecthomas** [comment]
Wait, why did you need to pass your EM instance to your components? They should just be data containers, with all logic in the systems.

**Comment by alecthomas** [comment]
Ping.

**Comment by roig** [comment]
Hello, Alecthomas.

I need to pass my EM instance to one of my components, the Transform component. I know this is not a pure data container, but this component have the list of children and parent Entity, so I need to acces the transform component of those internally so I need the EM instance.

I can't change this component right now, because changing this will cascade a major refactor :(

**Comment by roig** [comment]
I'm closing this, using the id of the entity solved the problem :+1:
