### ISSUE TITLE
Get notified when an entity is added or removed from a component family

### ISSUE THREAD

**Issue by Samdze** [alecthomas/entityx#144]
I thought it would be useful to have built-in events to get notified when an entity is added or removed from a component family. When there's a system that requires several components to work and to initialize data (for example a box2D Body that requires a Transform Component, RigidBody, Collider...) it becomes annoying to check everytime if an entity has all the components needed. This could also lead to an efficient iteration between entities that only belong to a specified component family maintaining a list of valid entities for each. This is how entity iteration is handled in Artemis and in Ashley (Java). At first glance I didn't notice this feature in EntityX.

**Comment by alecthomas** [comment]
Don't events, like [ComponentAddedEvent](https://github.com/alecthomas/entityx/blob/master/entityx/Entity.h#L309) cover that?

**Comment by alecthomas** [comment]
Also, you don't need to check if an entity has all of the required components, that's what `entities_with_components<C0, C1, ...>` does for you: it iterates over entities that have all of those components.

**Comment by Samdze** [comment]
Not exactly. The "EntityAddedToFamilyEvent" and the "EntityRemovedFromFamilyEvent" should be signs that the system can begin/stop his work on that entity, but not only his frame by frame work. I'll use Box2D again as an example: the Physics system requires both Transform and RigidBody components to work. If I add a RigidBody component to an entity is not yet time to initialize the Box2D Body in the Box2D world, the Body has to be initialized only when both components are being added to the entity. Same thing for components removal. If I remove the RigidBody component from a "valid" (from the Physics system prospective) entity I would surely have to destroy the Box2D Body from the Box2D world, but also if I only remove the Transform component from the entity. This is how component family events work, they only act when needed, without time-consuming iterations on entities that may not even have to change. ComponentAddedEven and ComponentRemovedEvent do not cover this entirely. In fact, family component events would cover both ComponentAddedEvent/ComponentRemovedEvent functions and also the more complex ones.
Just configure a "FamilyListener" object to listen to events related to a family formed by a single type of component and the entire functions of the per-component events are covered.
Pseudo code:
```
Family family = Family::all<Transform>().get();
TransformListener tListener(family); //TransformListener is a class created by the user that implements FamilyListener callbacks
engine.subscribe(tListener); //Now when a Transform is added/removed from an entity TransformListener callbacks will be called

//
//

Family fPhysics = Family::all<Transform, RigidBody>().get();
PhysicsListener pListener(fPhysics); //PhysicsListener is a class created by the user that implements FamilyListener callbacks
engine.subscribe(pListener); //Now when a Transform and a RigidBody are at the same time in the same entity the addedToFamily callback is called once

//When one of those components is removed from the entity the removedFromFamily will be called
//Then addedToFamily callback will be called again if Transform and RigidBody come back together in the same entity, and so on
```
Is up to the system to configure his FamilyListener(s).
No coincidence that those are the only events supported by Ashley framework.

**Comment by alecthomas** [comment]
Ah, it makes more sense now that you've described what an entity family is.

It looks like an interesting approach, but I believe it can be implemented on top of existing functionality (see below). This emits `Family<C...>::Added` and `Family<C...>::Removed` events when the set of components meets the family requirements and stops meeting them, respectively.

This is likely not identical implementation wise, but provides a similar interface.

```c++
template <typename ... Components>
struct Family {
  struct Added {
    ex::Entity entity;
  };

  struct Removed {
    ex::Entity entity;
  };

  Family(ex::EntityManager &entities, ex::EventManager &events) : entities_(entities), events_(events) {
    add_receivers<Components...>();
  }

  // Iterate over all entities from this family.
  ex::EntityManager::View<Components...> entities() {
    return entities_.entities_with_components<Components...>();
  }

private:
  struct BaseReceiver {
    virtual ~BaseReceiver() {}
  };

  template <typename C>
  struct Receiver: BaseReceiver, public ex::Receiver<C> {
    Receiver(Family &family) : family_(family) {}

    virtual ~Receiver() {}

    void receive(const ex::ComponentAddedEvent<C> &e) {
      family_.component_added(e.entity);
    }

    void receive(const ex::ComponentRemovedEvent<C> &e) {
      family_.component_removed(e.entity);
    }

  private:
    Family family_;
  };

  template <typename C>
  void add_receivers() {
    Receiver<C> *receiver = new Receiver<C>(*this);
    events_.subscribe<ex::ComponentAddedEvent<C>>(*receiver);
    events_.subscribe<ex::ComponentRemovedEvent<C>>(*receiver);
    receivers_.push_back(receiver);
  }

  template <typename C, typename C0, typename ... Cn>
  void add_receivers() {
    add_receivers<C>();
    add_receivers<C0, Cn...>();
  }

  template <typename C>
  bool has_components(ex::Entity entity) {
    return entity.has_component<C>();
  }

  template <typename C, typename C0, typename ... Cn>
  bool has_components(ex::Entity entity) {
    return has_components<C>(entity) && has_components<C0, Cn...>(entity);
  }

  void component_added(ex::Entity entity) {
    if (has_components<Components...>(entity)) {
      events_.emit(Added{entity});
    }
  }

  void component_removed(ex::Entity entity) {
    if (has_components<Components...>(entity)) {
      events_.emit(Removed{entity});
    }
  }

  std::vector<BaseReceiver*> receivers_;
  ex::EntityManager &entities_;
  ex::EventManager &events_;
};

```

**Comment by Samdze** [comment]
Yes, something like that should work. But It would be also great to have this feature built-in.
Like I said before, this approach opens the possibility of processing only entities that meet the requirements without having to check the requirements themselves every frame on every entity (this may be time consuming in case of large amounts of entities), only on components added/removed events. You should just keep a list of entities that meet the requirements and update it only on family events. This may also be implemented on top of EntityX, I just thought it would be very nice to have this feature out of the box because it covers everything EntityX currently covers and more.
Ashley (Java) handles this situation in this way:
```
public class MovementSystem extends EntitySystem {
    private ImmutableArray<Entity> entities;

    private ComponentMapper<PositionComponent> pm = ComponentMapper.getFor(PositionComponent.class);
    private ComponentMapper<VelocityComponent> vm = ComponentMapper.getFor(VelocityComponent.class);

    public MovementSystem() {}

    public void addedToEngine(Engine engine) {
        entities = engine.getEntitiesFor(Family.all(PositionComponent.class, VelocityComponent.class).get());
    }

    public void update(float deltaTime) {
        for (int i = 0; i < entities.size(); ++i) {
            Entity entity = entities.get(i);
            PositionComponent position = pm.get(entity);
            VelocityComponent velocity = vm.get(entity);

            position.x += velocity.x * deltaTime;
            position.y += velocity.y * deltaTime;
        }
    }
}
```
An array of valid entities is automatically mantained, and every system can handle every amount of families it wants freely.
