### ISSUE TITLE
Compilation fails on GCC 6.1

### ISSUE THREAD

**Issue by andresmanz** [alecthomas/entityx#145]
> **/entityx/3rdparty/catch.hpp:3517:99: error: throw will always call terminate()** [-Werror=terminate]
>                              throw std::logic_error( "Only one unpositional argument can be added" );
> 
> **note:** in C++11 destructors default to noexcept

There is a throw() in Catch's ArgBinder destructor. Doesn't seem to be the case in the current version of Catch.

**Comment by iamPHEN** [comment]
+1 to this. Updating catch will also suppress this same warning that appears on VS2015 .  

I have some spare cycles this weekend to make a PR if no one else can get to this by then.

**Comment by iamPHEN** [comment]
I've made a pull request, but I don't quite a machine to setup with GCC 6.1, perhaps we can add Travis configs for that?

**Comment by jarrettchisholm** [comment]
I can reproduce this as well (using `gcc version 6.2.1 20161124 (Debian 6.2.1-5)`).

I'm not sure how correct this solution is, but uncommenting the `noexcept(false)` bit on line 3507 of `catch.hpp` seems to get it to compile.  The tests all ran successfully on my system.

**Comment by jarrettchisholm** [comment]
Submitted a possible workaround for this issue in #167.

**Comment by alecthomas** [comment]
Thanks   for that. Seems reasonable.
