### ISSUE TITLE
experimental/compile_time branch fails to build in VS2015

### ISSUE THREAD

**Issue by RallyTronics** [alecthomas/entityx#148]
I get an internal compiler error on line 838 of entityx.hh  when building the sample project in debug or release.  Has anyone had success building this in VS?

This is the line

```
/**
   * Find Entities that have all of the specified Components and assign them
   * to the given parameters.
   *
   * @code
   * Component<Position> position;
   * Component<Direction> direction;
   * for (Entity entity : entity_manager.entities_with_components(position, direction)) {
   *   // Use position and component here.
   * }
   * @endcode
   */
  template <typename ... ComponentsToFilter>
  UnpackingView<ComponentsToFilter...> entities_with_components(Component<ComponentsToFilter> & ... components) {
    ComponentMask mask = component_mask<ComponentsToFilter...>();
    return UnpackingView<ComponentsToFilter...>(this, mask, components...);
  }
```

**Comment by alecthomas** [comment]
Can you clean up that example? I can't tell what it means.

**Comment by RallyTronics** [comment]
Not sure what you mean by clean up that example.  I just copy/pasted it out of your header file.  I am just trying to build the entity_test project from your repo.

**Comment by alecthomas** [comment]
I meant block quote the text so it's not garbled. I've done it.

The compile_time branch won't work on stock VS2015, you need a very recent version with all CTPs applied.

**Comment by RallyTronics** [comment]
Ok, thanks!
