### ISSUE TITLE
Reinitialize systems to default values

### ISSUE THREAD

**Issue by mikke89** [alecthomas/entityx#152]
Hi, and thanks for making this awesome little tool!

I have more of a question here than an issue. I am wondering what the best way of reinitializing some of my system classes is? 

The best case for me would be to just delete the systems and add them again, as this would initialize them easily, but there doesn't seem to be support for doing this. I have many system classes with various member variables that I need their default values after e.g. loading up a new level in the game. I would very much prefer to not have to do this manually for each class.

Having looked over the SystemManager in entityx... I wonder, is it possible to just remove my own system from the systems list in SystemManager? Or is there something else I should think about before doing this?

**Comment by alecthomas** [comment]
The SystemManager is very thin, so you can easily implement your own to achieve this behaviour.
