### ISSUE TITLE
`std::hash<const entityx::Entity>` missed.

### ISSUE THREAD

**Issue by FrankStain** [alecthomas/entityx#153]
Hi, @alecthomas !
So, i had faced the issue that `std::hash<const entityx::Entity>` was not declared at the moment i had tried to use `std::unordered_map<const entityx::Entity, uint32_t>` type.
I don't wish allow future modifications of components from entities stored this way, so i prefer to use `const entityx::Entity` type.

How about implementing `std::hash<const entityx::Entity>` by default near to `std::hash<entityx::Entity>`?

**Comment by alecthomas** [comment]
Seems reasonable, a PR would be welcome.
