### ISSUE TITLE
Conan Support

### ISSUE THREAD

**Issue by RussTheAerialist** [alecthomas/entityx#158]
I'm not sure if this project is still actively under development but I'm planning to use it in a game that I'm making.  I am using conan, so I've created a [conanfile](https://github.com/RussTheAerialist/conan-entityx) for it, and the package is published on [conan.io](https://www.conan.io/source/EntityX/1.2.0/RussTheAerialist/test) but I only have it working for OSX since that's my current target for me game.

**Comment by alecthomas** [comment]
Thank you.
