### ISSUE TITLE
EntityX with Cocos2D Android

### ISSUE THREAD

**Issue by Silvest89** [alecthomas/entityx#161]
Anyone gotten it to work with it?
I have gotten it to work just on the win32 version. 
Have been trying to get it to work with Android seems to get alot of undefined references.

**Comment by FrankStain** [comment]
Hey, @Silvest89 . We have already get it work inside of cocos. But we didn't make EntityX as cocos plugin.
EntityX feels free itself as standalone library. :)

You must only enable c++11/14 support for your build system.

For android it may be done like:
```
# APP_CPPFLAGS := -std=c++14
APP_CPPFLAGS := -std=c++11
```

**Comment by Silvest89** [comment]
Could you post the full steps you did to get it to work ?
I have been at this for 2 full days :P

**Comment by Silvest89** [comment]
Hey @FrankStain ,

Could you post the full steps you did to get it to work ?
I have been at this for 2 full days :P
Cocos is so messy :/

**Comment by FrankStain** [comment]
> Cocos is so messy :/

Can't disagree with you ))

So, about your errors at compilation. All says that you just forgot the sources of EntityX...
Did you make the separate Android.mk for EntityX static library?
Did you include dependencies on EntityX static library into your main project?

Show Android.mk of your main project. Let's try to fix it.

**Comment by Silvest89** [comment]
Got it to compile now :)

Just edited the main mk file.

```
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

$(call import-add-path,$(LOCAL_PATH)/../../cocos2d)
$(call import-add-path,$(LOCAL_PATH)/../../cocos2d/external)
$(call import-add-path,$(LOCAL_PATH)/../../cocos2d/cocos)
$(call import-add-path,$(LOCAL_PATH)/../../cocos2d/cocos/audio/include)

LOCAL_MODULE := MyGame_shared

LOCAL_MODULE_FILENAME := libMyGame

LOCAL_SRC_FILES := hellocpp/main.cpp \
                   ../../Classes/AppDelegate.cpp \
                   ../../Classes/HelloWorldScene.cpp \
                   entityx/Entity.cc  \
entityx/Event.cc  \
entityx/System.cc \
entityx/help/Pool.cc \
entityx/help/Timer.cc \

LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../Classes \
entityx/Entity.h  \
entityx/Event.h  \
entityx/System.h \
entityx/help/Pool.h \
entityx/help/Timer.h \

# _COCOS_HEADER_ANDROID_BEGIN
# _COCOS_HEADER_ANDROID_END


LOCAL_STATIC_LIBRARIES := cocos2dx_static \

# _COCOS_LIB_ANDROID_BEGIN
# _COCOS_LIB_ANDROID_END

include $(BUILD_SHARED_LIBRARY)

$(call import-module,.)

# _COCOS_LIB_IMPORT_ANDROID_BEGIN
# _COCOS_LIB_IMPORT_ANDROID_END
```

**Comment by FrankStain** [comment]
```
LOCAL_C_INCLUDES := $(LOCAL_PATH)/../../Classes \
entityx/Entity.h  \
entityx/Event.h  \
entityx/System.h \
entityx/help/Pool.h \
entityx/help/Timer.h \
```

Looks horrible )) All .h files are redundant here. Also, as i see, you had placed EntityX just into your project. So, `$(LOCAL_PATH)/../../Classes` must be enough for successful compilation.

**Comment by FrankStain** [comment]
In addition.
As you say the compilation is successful, you may feel free to close the issue.

But before i have to tell your `Android.mk` is not canonical at this moment. @Silvest89 , how are you familiar with ndk?

First thing, at the begin of your `Android.mk` you set the directories of your libraries. There may be one for EntityX library too. Just place the EntityX entire repo into `$(LOCAL_PATH)/../../entityx` folder.
```
$(call import-add-path,$(LOCAL_PATH)/../..)
```
There is official `Android.mk` at the rot of EntityX repo, so this path will be valid.
Or you may place it into `$(LOCAL_PATH)/../../cocos2d/external` folder.

I just noticed that `Android.mk` don't export include directories, but it will be much better if it will.
Hey, @alecthomas , how about making small fix in `Android.mk` of EntityX? :)
Just like this.
```
LOCAL_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_C_INCLUDES)
```

And the final instruction will declare the dependency on EntityX library for your main project.
```
LOCAL_STATIC_LIBRARIES := cocos2dx_static \
entityx \

...

include $(BUILD_SHARED_LIBRARY)

$(call import-module,.)
$(call import-module,entityx)
```

So, at the next build the EntityX must be built into separate static library and linked into your main binary without problems.

**Comment by Silvest89** [comment]
Thanks for the headsup. As someone who is coming from Java and has been away from C++ xD first time dealing with NDK.
