### ISSUE TITLE
Feature request for: entities.entities_with_components( c ).size()

### ISSUE THREAD

**Issue by visorz** [alecthomas/entityx#164]
Thank you a lot for your clear and clean library. I am using it for my computer graphics lab program and it is the best solution for a clean and easy to read program architecture.

I would like to count entities and instead of writing:

    entityx::ComponentHandle<Position> pos;
    auto begin = entities.entities_with_components( pos ).begin();
    auto end = entities.entities_with_components( pos ).end();
    const auto modelCount = std::distance( begin, end );

I would like to use a shorter form:

    entityx::ComponentHandle<Position> pos;
    const auto modelCount = entities.entities_with_components( pos ).size();

And because internally components are vectors, I guess you could realise this in an easy way.

**Comment by alecthomas** [comment]
You should use [std::distance](http://www.cplusplus.com/reference/iterator/distance/). A size() method would be basically doing the same thing as the component vectors can have holes.
