### ISSUE TITLE
Capturing base class of derived components in EntityManager::each() 

### ISSUE THREAD

**Issue by Belfer** [alecthomas/entityx#171]
Probably not the right section to post this, however I couldn't find anything better, please let me know of a better way if there is.

I'm looking into capturing components as their base class, for example, an entity with component sf::Sprite which derives from sf::Transformable and sf::Drawable. I'm not able to capture it via;

`es.each<sf::Drawable>([=](ex::Entity entity, sf::Drawable& drawable) {});`

**Comment by alecthomas** [comment]
When you assign the object, do you specify it as an `sf::Drawable`?

**Comment by Belfer** [comment]
No, it is as `sf::Sprite`, and by the sounds of that, I'm guessing it's not possible?

**Comment by alecthomas** [comment]
This will work:

```c++
sf::Sprite sprite = ...;
entity.assign<sf::Drawable>(sprite);
es.each<sf::Drawable>(...);
```

This will not work:

```c++
sf::Sprite sprite = ...;
entity.assign<sf::Sprite>(sprite);
es.each<sf::Drawable>(...);
```

I can't imagine why you would want to do this though.

**Comment by Belfer** [comment]
I want to access components by their base class in this case sf::Drawable and sf::Transformable separately, but add the components as sf::Sprite or any class that inherits from these two.

**Comment by FrankStain** [comment]
> I want to access components by their base class

@Belfer , hey!
This point breaks the ECS paradigm. You have to rid of the inheritance when working on components. It's much better when each component have no base class and all components of entity are placed directly as entity components.

Why would you like to use inheritance for components?

**Comment by Belfer** [comment]
Hi @FrankStain , well, I wanted to have a generic way to update `sf::Transformable`'s and then draw `sf::Drawable`'s without having to know the specific type, say `sf::Sprite` for instance, that way I make sure all components with base of these two types are updated correctly. I can live without this feature if there's no easy way for me to do it. If I can think of a seriously good reason to need this I'll let you know. Thanks for all the help!

**Comment by alecthomas** [comment]
That's what my first example does, though you will probably need it to be a pointer/shared_ptr.

**Comment by Belfer** [comment]
That actually flew above my head, well at least this opens up some possibilities and I think I can make work, but the pointers might be a bit of a hassle. I'll see if I've any luck implementing it, thanks again!

**Comment by alecthomas** [comment]
Ah, ok that makes sense then.

In that case, you can see basically what you need to do in the example code. [Here's](https://github.com/alecthomas/entityx/blob/master/examples/example.cc#L51) the declaration of the "component". [Here's](https://github.com/alecthomas/entityx/blob/master/examples/example.cc#L98) an `sf::CircleShape` being assigned to an entity as a `Renderable`.
