### ISSUE TITLE
[Bug?] ~EntityX() is not calling on_destroy event.    (compile_time branch)

### ISSUE THREAD

**Issue by roig** [alecthomas/entityx#175]
Hello alecthomas, if you create an entity without any component and set the callbacks for on_create and on_destroy. It calls on_create callback correctly, but when my program exits, the destructor is not calling on_destroy callback.

I debugged, and found that is not entering inside the "if" (see the code), maybe because the entity has no components, i think it should call on_destroy without components attached to the entity, but I'm not sure how to fix it, any ideas ?
```
  ~EntityX() {
    for (std::size_t i = 0; i < entity_component_mask_.size(); i++)
      if (entity_component_mask_[i].any())
    	  destroy(Id(i, entity_version_[i]));
  }
```

Thank you!

**Comment by iamPHEN** [comment]
Can you check if your hitting issue #28?  Symptoms sound similar.

**Comment by roig** [comment]
Hello, i checked that issue, but no, I think it isn't related. This code is from the "compile_time" branch, the code is completely different.

The conditional is wrong I think, because it is checking every entity that has a component, but what about destroying entities that doesn't have a component? We will have to wait for alec, to check that.

thanks.

**Comment by alecthomas** [comment]
@roig you are correct that the destructor is not called, though this is somewhat intentional. EntityX maintains a free list of deleted entity slots, so to determine whether an Entity is truly valid that list needs to be walked for each ID. This could be very slow depending on the number of entities in the free list.

That said, it's still a bug.

**Comment by roig** [comment]
Thank you alec!
