### ISSUE TITLE
[bug?] Entity destruction not calling on_component_removed() for every component assigned.

### ISSUE THREAD

**Issue by roig** [alecthomas/entityx#179]
Maybe it's intentional, but destroying an entity is not calling the function call on_component_removed for each assigned components when those are removed from the entity.

Now I'm forced to check for every component inside on_entity_destroyed, and call my on_component_removed callback for each component.

I think entityx should handle this, because now the behavior seems inconsistent. 
- If you call remove<..>() from an Entity, the component is removed from entity and callback is called.
- If you call destroy() from an Entity, the component is removed from the entity and NO callback is called.
What do you think?

**Comment by alecthomas** [comment]
`destroy()` should definitely call `on_component_removed()`.

There are some bugs in the compile_time branch. See also #176. I've been a bit sick lately, so haven't had time to fix these issues. PRs welcome!

**Comment by roig** [comment]
I hope you get better soon! :+1:

**Comment by roig** [comment]
Hello Alec, yesterday I was trying to fix this, but I don't know how can I iterate for all the existing components of an entity and call .remove<C>() on each of them. I know I have to use the components mask, but how can I iterate that templated tuple? 

P.D. I'm a noob with templates : D

**Comment by zackthehuman** [comment]
@roig Are you only working in the compile_time branch or off of master?

**Comment by alecthomas** [comment]
@zackthehuman yes, this is explicitly for the compile_time branch.

@roig I started working on this last night. Hopefully I'll be done by tonight.

**Comment by alecthomas** [comment]
(also, yes, it needs some template magic)

**Comment by alecthomas** [comment]
I've been looking at this, and it turns out to be a lot more difficult than one would hope :\.

**Comment by roig** [comment]
Hello alec, I have been looking at this too, and I think that the destruction of each component should be there: 

`template <class Components, class Storage, std::size_t Features>
inline void EntityX<Components, Storage, Features>::destroy(Id entity) {
  assert_valid(entity);
  //DESTROY HERE EACH ASSIGNED COMPONENT FOR THAT ENTITY

  entity_destroyed_(Entity(this, entity));
  const std::uint32_t index = entity.index();
  ComponentMask mask = entity_component_mask_[index];
  Components::template destroy<Storage>(storage_, mask, index);
  entity_component_mask_[index].reset();
  entity_version_[index]++;
  free_list_.push_back(index);
}
`

Am I wrong?

**Comment by alecthomas** [comment]
@roig give that latest commit a whirl. Also, feel free to jump into Gitter if you need more interactive assistance.
