### ISSUE TITLE
Enable and disable systems

### ISSUE THREAD

**Issue by MatillaMartin** [alecthomas/entityx#180]
When using many systems in a complex game, the update cycle is bloated with systems that only update components rarely, for example particle sprites for sparks or dust.

Is there a way to enable and disable systems when one knows that the system will be idling trying to update a empty component list?

**Comment by alecthomas** [comment]
The system management infrastructure is very simple, so to cater for non-trivial cases it's probably just easier to roll your own. You can see this in the [Application class](https://github.com/alecthomas/entityx/blob/experimental/compile_time/examples/example.cc#L372) in the compile time branch, which is basically identical to `SystemManager`.
