### ISSUE TITLE
What is the state of this library?

### ISSUE THREAD

**Issue by ArekPiekarz** [alecthomas/entityx#202]
I would like to ask what is the current state of this library? I can see the last release was done 2.5 years ago and the last commit on a  branch almost 5 months ago. Is it still being maintained? Is there any plan to make another release?

**Comment by alecthomas** [comment]
The library is basically stable. Most people have been using master AFAICT, which is fine with me.

**Comment by ArekPiekarz** [comment]
What about the question about another release? Also, are you going to merge the compile-time experimental branch?

**Comment by L3nn0x** [comment]
I'm using the compile time branch, which is working just fine.
