### ISSUE TITLE
std::sort with Entities

### ISSUE THREAD

**Issue by Jakobzzz** [alecthomas/entityx#203]
Hey,

I have a problem wiht std::sort when I want to sort all the entities by a component attribute. This is what I have at the moment:

```
ComponentHandle<Render> render;
std::sort(m_entities.entities_with_components(render).begin(), m_entities.entities_with_components(render).end(),
[](const Render & a, const Render & b) { return a.layer < b.layer; });
```
But it's not the correct way and I can't wrap my head around it. Do you have any suggestions?

Thanks.

**Comment by zackthehuman** [comment]
if I understand correctly, you are trying to get a sorted list of all `Render` components. When you use `entities_with_components` what you get is a _view_ and a set of iterative that walk that _view_. The underlying storage for components isn’t really sortable as far as I know, so I think your best bet would be to use `entities_with_components` and copy all of the entries into a container of your own which you can then sort. Sorting a _view_ doesn’t make much sense.
