### ISSUE TITLE
"entityx::EntityManager" has no member "each"

### ISSUE THREAD

**Issue by K4kug3n** [alecthomas/entityx#204]
Hi everyone,
I installed EntityX recently, but i'm in trouble.
I tried to compile the next exemple code :

![temp](https://user-images.githubusercontent.com/36965966/36860272-197909fe-1d81-11e8-95fa-0288b25cf862.png)

But it doesn't run, the function "each" of EntityManager isn't reconized.
I don't find this function in the definition of the class EntityManager too, so i don't know what to do
(This code work without the definition of "MovementSystem" so i think my linking is good)

If anyone can help me,
Thanks for read/help
(Sorry for this begginer english xd)
Kakugen

**Comment by L3nn0x** [comment]
I see it in the EntityManager class : https://github.com/alecthomas/entityx/blob/master/entityx/Entity.h#L765 so I'm not sure what the problem is. Which version of VS are you using?

**Comment by K4kug3n** [comment]
I use MSVC 2017 free edition, on W10
I checked in my Entity.h, and its completly different...
My line 765, where is the .each definition in your file, is "friend class ComponentHandle;", 
This line is present in your file at the line 838
It's really strange, i don't have the same file

**Comment by L3nn0x** [comment]
No problem, always keep your files updated with the latest version from github ;)

**Comment by hak33m16** [comment]
I don't believe this was his fault. I just ran into it as well in W10 using CMake for VS 2017 with the entityx 1.1.2 package. The most recent release package listed on Github was 1.1.2, but there was a little ... icon that I could click on this page https://github.com/alecthomas/entityx/releases so I would say it's a design issue on Github's end.
