### ISSUE TITLE
Can't build and install

### ISSUE THREAD

**Issue by Raigiku** [alecthomas/entityx#205]
After using cmake with MinGW 6.3 on windows and trying to use "make" to build I get this error:
![image](https://user-images.githubusercontent.com/31873735/37249946-8b58487e-24bf-11e8-8184-a3a06b9ff64d.png)

**Comment by alecthomas** [comment]
Disable the tests.

**Comment by Raigiku** [comment]
It fixed that but now I get this:
![image](https://user-images.githubusercontent.com/31873735/37250007-ade7e34e-24c0-11e8-8e9d-8c03813e9f74.png)
