### ISSUE TITLE
Error when building with CMake 

### ISSUE THREAD

**Issue by MarconatoB** [alecthomas/entityx#217]
Using macOS High Sierra 10.13.6
Following the Installation guide in README.md, I get the following error when building entityx with the command "make", after typing "cmake" (No flags used).

In file included from /Users/username/entityx-1.1.2/entityx/Event_test.cc:15:
/Users/username/entityx-1.1.2/entityx/3rdparty/catch.hpp:3517:29: error: 
      '~ArgBinder' has a non-throwing exception specification but can still
      throw [-Werror,-Wexceptions]
                            throw std::logic_error( "Only one unposition...
                            ^
/Users/username/entityx-1.1.2/entityx/3rdparty/catch.hpp:3823:13: note: 
      in instantiation of member function
      'Catch::Clara::CommandLine<Catch::ConfigData>::ArgBinder::~ArgBinder'
      requested here
        cli.bind( &ConfigData::showHelp )
            ^
/Users/username/entityx-1.1.2/entityx/3rdparty/catch.hpp:3507:13: note: 
      destructor has a implicit non-throwing exception specification
            ~ArgBinder() /* noexcept(false) */ {
            ^

Any help would be appreciated.

**Comment by alecthomas** [comment]
Try running cmake with `-DENTITYX_BUILD_TESTING=0`

**Comment by MarconatoB** [comment]
Thanks, it worked! But why?
