### ISSUE TITLE
Does not compile on Windows with Visual Studio 2013

### ISSUE THREAD

**Issue by jarrettchisholm** [alecthomas/entityx#23]
Does not compile on Windows with Visual Studio 2013.
1. First issue was gcc specific compiler flags.  To remove:
2. go to Project -> Properties -> Configuration Properties -> C/C++ -> Command Line
3. Remove all the flags in the 'Additional Options' box
4. Second issue: Cannot open include file: 'unistd.h': No such file or directory
   I think `unistd.h` is unix only.  Need to find a replacement for Windows.
5. After commenting out the first `unistd.h` include I saw (in `simplesignal.h`), I get lots of errors - 648 to be exact.
   Some of them I think are just missing includes.  Some of them, I'm not sure if VS doesn't support some C++11 features?  For example, in `simplesignal.h`, I get an error for this bit of code:

```
/// CollectorInvocation specialisation for regular signals.
template<class Collector, class R, class... Args>
struct CollectorInvocation<Collector, R (Args...)> {
  inline bool
  invoke (Collector &collector, const std::function<R (Args...)> &cbf, Args... args)
  {
    return collector (cbf (args...));
  }
};
```

The errors are:
1. Error    12  error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
2. Error    13  error C2143: syntax error : missing ',' before '<'

**Comment by Clavotro** [comment]
Hello, 
I am keen to use entitiyx on windows with Visual Studio 2013 too. I am having issues getting the sample program to compile. I have LNK errors such as 

"Error	13	error LNK2001: unresolved external symbol "public: static unsigned int entityx::BaseSystem::family_counter_" (?family_counter_@BaseSystem@entityx@@2IA)"

and

"Error	3	error LNK2019: unresolved external symbol "public: virtual __thiscall entityx::EventManager::~EventManager(void)" (??1EventManager@entityx@@UAE@XZ) referenced in function __unwindfunclet$??0EntityX@entityx@@QAE@XZ$0"

Usually with other  add-ons I have used (like SFML) I would add the appropriate .libs to fix this, but I cannot find any in the entitiyx folder. What should I do to fix this?

Thanks

**Comment by alecthomas** [comment]
Have you used cmake to compile it? I'm not 100% sure of how to do this on Windows, but you definitely need to build with cmake to get libraries.

**Comment by Clavotro** [comment]
I have not used cmake to compile it. Thanks, I did not know I need to do this to get the libs, I will give that a go.

**Comment by Clavotro** [comment]
Hello, Using CMake I have managed to get this running using Visual Studio 2013. I am not 100% it is error free though. When the program starts, I see a huge particle explosion in the top left that fades away after about 3 seconds. Apart from that the program remains black. 

I can actually get it working if I change your random function to this "return static_cast<float>(std::rand() % (a*10)/10);" I am not sure the reason behind this behavior. What numbers are is the random system meant to put out? Thanks for your help and program.

**Comment by alecthomas** [comment]
Interesting. It might be some difference in compiler behaviour with implicit casting. Annoying. The 1000 is just so it returns fractional floating point numbers up to 3 decimal places.
