### ISSUE TITLE
Future of entityx

### ISSUE THREAD

**Issue by NukeBird** [alecthomas/entityx#233]
Is this project alive?
If yes, please tell us on what you working on and where you need help
If no, can I know the reason of this and your opinion it total?

Thanks for your attention

**Comment by deflinhec** [comment]
I’m still working with mobile app game

**Comment by alecthomas** [comment]
EntityX is pretty stable, with no major issues. I don't have any current projects that use it, so I personally don't need any new features. If you'd like to contribute, having a look at the issues and seeing if there any low hanging fruit, send through PRs, etc. would be very helpful. A good start might be #224.

**Comment by sigzegv** [comment]
> Is this project alive?
> If yes, please tell us on what you working on and where you need help
> If no, can I know the reason of this and your opinion it total?

 Why a stable project that makes the job would ever need to be updated or show an alive status ?

**Comment by maluramichael** [comment]
As long as @alecthomas anwers on issues and occasionally merges a pr iam happy with the current state of the project.

**Comment by bensanmorris** [comment]
It's a very stable ECS impl. Been using it personally in a side-project without issues. Alec monitors PRs and supplies feedback. +1 from me :-)
