### ISSUE TITLE
How to create entites inside systems?

### ISSUE THREAD

**Issue by tree786** [alecthomas/entityx#249]
hi

I was wondering  how to create entities inside of systems. I.e. take the following system:
```
struct MovementSystem : public System<MovementSystem> {
  void update(EntityManager &es, EventManager &events, TimeDelta dt) override {
    es.each<Position>([](Entity entity, Position &position) {
    //create entity
      entx.entities.create().assign<Position>(45.0,12.9);
    });
  };
};
```
^^ where `entx` refers to `EntityX` class, but that doesn't seem to work. Is there a way to spawn  an entity using `EntityManager` instead?

Thanks

**Comment by alecthomas** [comment]
The EntityManager is passed as a parameter, is that not sufficient?

**Comment by tree786** [comment]
> Is there a way to spawn an entity using `EntityManager` instead?
>

**Comment by alecthomas** [comment]
I guess I don't understand what the issue is. The signature of the function includes the EntityManager:

```c++
  void update(EntityManager &es, EventManager &events, TimeDelta dt) override {
```

You can just call:

```c++
auto new_entity = es.create();
```

Is that what you're looking for?

**Comment by tree786** [comment]
Thanks ! That's exactly what was after. I'll close this now

**Comment by alecthomas** [comment]
Here's some code from the example: https://github.com/alecthomas/entityx/blob/master/examples/example.cc#L89
