### ISSUE TITLE
Copy constructor for Entity::assign(..) method?

### ISSUE THREAD

**Issue by jarrettchisholm** [alecthomas/entityx#37]
Hi,

What do you think about bringing back the `Entity::assign(component)` method?  Basically, it would just call the copy constructor of the component type `C`, so the memory would still be managed by Entity X, but you could send in a fully created object instead of having to send in each parameter of the object.

The only downside (I see) is that the user of the library would have to be cognizant of the fact the component was _copied_.

I ask, as my code currently uses the old assign method, and it's just much easier for me :)  I would have no problem whipping up a pull request for this feature.

Cheers

**Comment by omikun** [comment]
Sorry to dredge this up, but what is the proper way of calling assign_from_copy?

For instance, I tried both of these:
```
1. shadow.assign_from_copy(myShip.component<Ship>());
2. shadow.assign_from_copy(myShip.component<Ship>().get());
3. const Ship* myshipship = myShip.component<Ship>().get();
   shadow.assign_from_copy(&myshipship);

assert(shadow.has_component<Ship>());
```
but it never gets passed the assertion. I am running in xcode on 10.10
