### ISSUE TITLE
Windows Visual Studio DLL export support

### ISSUE THREAD

**Issue by kumar8600** [alecthomas/entityx#57]
We have no dll export support now.

We should add dllexport, dllimport declaration for each functions and class we want to public.

**Comment by Gronis** [comment]
I'm currently trying to get entityx running on my windows machine. CMake doesn't do the job for me. Anyhow if someone knows how to setup entityX with cmake on a windows machine, could someone expain to me? Though I guess it doesn't work at all atm since it hasn't been tested

**Comment by alecthomas** [comment]
EntityX compiles fine under Visual Studio. It has been tested and used by users with [success](https://github.com/alecthomas/entityx#installation).

**Comment by Gronis** [comment]
My bad, I'm using Visual Studio 2012. I missed out on the version requirement on Visual Studio 2013 or later. Thanks anyway!

**Comment by roig** [comment]
In a crossplatform project, In windows I need Entityx to export the classes/functions to use my DLL with another project.

I know you closed this, but.. I think this feature is needed for windows usage.

**Comment by alecthomas** [comment]
I'd accept a PR for it for sure.

**Comment by roig** [comment]
Ok,I will try to get it done. Thanks :+1:
