### ISSUE TITLE
Eventless Entity System

### ISSUE THREAD

**Issue by asmodehn** [alecthomas/entityx#64]
After some experience using entityx, Events allow me to mess up the nice design I could have in entity systems, if I just spent more time looking for a proper solution rather than just going for the easy "Oh I'll implement an event and do it there..." approach.

-> If Events are not necessary to a completely functioning entityx, I would like to get rid of them, to simplify entityx and avoid potential pitfalls. Note : I now favor using lambda callbacks in components to signal something "out of the entity system domain". Compared to Events, I just need to be careful of the lifetime of the callback, as with any lambda.

**Comment by alecthomas** [comment]
I'm going to close this, as I'm pretty much decided on removing the general purpose event system. I'll provide some mechanism for observing changes to the system, but anything beyond that is out of scope.

FYI I also sent a mail to the ML describing a candidate approach for version 2.
