### ISSUE TITLE
Event Queue with EntityX?

### ISSUE THREAD

**Issue by IgnatusZuk** [alecthomas/entityx#71]
Hi again folks,

I'm curious on what your thoughts are on implementing an **Event Queue** with EntityX?
My biggest concern with it is the fact that events are processed at a later time, and systems only hear about certain events a frame too late.

In the EntityX *example.cpp* we emit **CollisionEvent** from the **CollisionSystem** and we catch it in the **ExplosionSystem**, storing collided entities in a list that will be updated once **ExplosionSystem::update()** is called. We heavily rely on the order of updates, specifically that **ExplosionSystem** is updated after the **CollisionSystem**.

    systems.update<CollisionSystem>(dt);
    systems.update<ExplosionSystem>(dt);

If this was the other way around we would miss one frame, entities would move one frame further into each other before finally exploding. (Probably not very visible, but a quite concerning issue). The same effect happens when we introduce an Event Queue into the equation.

One solution I see is to have systems do all necessary work on the receive event method; they don't wait for update().

Here's my own example with the problem of missing a frame:

    CollisionSystem::update(ex::TimeDelta dt) {
        //... check collisions
        events->queue<CollisionEvent>(e1, e2);
    }

    Application::update(ex::TimeDelta dt) {
        systems.update<CollisionSystem>(dt); //Queue CollisionEvent!!!
        systems.update<MovementSystem>(dt); //Nothing to resolve, okay keep moving
        systems.update<ParticleSystem>(dt); //Nothing to confettisize
        systems.update<RenderSystem>(dt); //Draw entities on top of each other
        systems.update<AudioSystem>(dt); //No sound to play
	
        event_queue.update(); //Now process CollisionEvent(e1,e2)
    }

![ss 2014-12-08 at 10 29 21](https://cloud.githubusercontent.com/assets/1710856/5348706/d71c95e2-7f29-11e4-901f-172264b856b4.png)

Is this a real issue or am I missing something really obvious?

**Comment by alecthomas** [comment]
I'm settling on the approach in [experimental/compile_time](https://github.com/alecthomas/entityx/tree/experimental/compile_time). Events are limited to basic change observation, with no extensibility.

**Comment by alecthomas** [comment]
I'm settling on the approach in [experimental/compile_time](https://github.com/alecthomas/entityx/tree/experimental/compile_time). Events are limited to basic change observation, with no extensibility.
