### ISSUE TITLE
Add new managers to update loop

### ISSUE THREAD

**Issue by Gronis** [alecthomas/entityx#80]
I think that you should be able to specify own Managers. Right now, you have EntityManager and EventManager. It would be nice if you could specify what managers you would like to use in the update loop and a way to create new Managers based on the code you have.

eg:
```
struct Level : EntityX<ShapeManager>{

}
```

```
struct SomeSystem : System<SomeSystem>{
    void update(ShapeManager &shapes, EntityManager &entities, 
            EventManager &events, double dt){
}
```

I don't know how hard this is or how useful it might be. But give the user availability to add their own Managers would be nice.

**Comment by alecthomas** [comment]
I think this should be a FAQ. Basically, systems are the System stuff is a very lightweight layer and rather than have it cater to everything it is easier to just roll your own. See #75 for an example.
