### ISSUE TITLE
unsubscribe Events

### ISSUE THREAD

**Issue by Gronis** [alecthomas/entityx#81]
I think there should be a way to unsubscribe a Receiver from an event like this
```c++
void update(EntityManager &entities, EventManager &events, double dt){
    if(/*some condition*/){
        events.unsubscribe<SomeEvent>(this);
    }
}
```

Alec if you think this is a good idea but don't want to do this yourself. I can possibly do it (if I have the skills) and submit a pull request.

**Comment by alecthomas** [comment]
There is some discussion of that in the [mailing list](http://librelist.com/browser//entityx/2014/10/29/unsubscribing-this-from-event-callback/). The current issue is that there is currently no tracking of the original type. All that is stored is the wrapping callback. You would also need to store a lookup from the receiver type family to the callback. I'd definitely welcome a PR though.

**Comment by Gronis** [comment]
I've made a pull request that hopefully fixes this issue. I don't really get how everything works, so I might have missed out on a couple of things. 

https://github.com/alecthomas/entityx/pull/84
