### ISSUE TITLE
Continuous Integration for Visual C++ build

### ISSUE THREAD

**Issue by kumar8600** [alecthomas/entityx#83]
[Appveyor](http://www.appveyor.com/) is CI service for Windows developers.

[bulletphysics/bullet3](https://github.com/bulletphysics/bullet3) uses it too.

:cake:

**Comment by alecthomas** [comment]
Looks useful, so I gave it a try. [It appears](https://ci.appveyor.com/project/alecthomas/entityx/build/1.0.5) that the version of Visual Studio is not recent enough for the C++11 features that EntityX requires. Or, at least, that is what I'm assuming from those compiler errors. EntityX compiles fine on my own Windows machine with the latest public version of VS.

**Comment by alecthomas** [comment]
Actually, disregard that, it just looks like it can't find the test solution... let me fiddle around with it a bit.

**Comment by kumar8600** [comment]
@alecthomas Thank you seems good.
