### ISSUE TITLE
Removing the need of inheriting from the Component and Event template classes.

### ISSUE THREAD

**Issue by Demon-In-A-Jar** [alecthomas/entityx#85]
Since the Event and Component template classes are only used in order to provide type-integer mapping, there is no actual need to make users derive from them when creating a new component or event type. The type-integer mapping can still be retained using the type information from templates since the family functions are static and not concerned with instance state.

**Comment by alecthomas** [comment]
Do you have an implementation example that can achieve this?

**Comment by Demon-In-A-Jar** [comment]
In general you can keep the Event/Component classes but the user doesn't need to derive for them since we only need the family ids from the instantiated template classes which don't require instance data. For Events for example, you can just change the CallbackWrapper and Signal signatures to take a pointer to void instead of EventBase. Notice how the signal_of function doesn't lose it's functionality with this change because the Event type is retained using templates and an event class instantiation happens automatically. As for Components, I don't think they are used through a BaseComponent pointer/reference anywhere so that should even work outside of the box to be honest even though I can't test this at this moment.

**Comment by alecthomas** [comment]
Interesting idea. I can't really think of any downsides or lost functionality. The implementation is [clean](https://github.com/alecthomas/entityx/compare/inheritance_free).
