### ISSUE TITLE
Use braced initialization when creating components

### ISSUE THREAD

**Issue by notlion** [alecthomas/entityx#87]
This is just a thought. If C++11's braced uniform initialization was used for internal component creation we could use structs without needing to write an explicit constructor.

```cpp
new(pool->get(id.index())) C{std::forward<Args>(args) ...};
```

Say we have a simple Point struct..
```cpp
struct Point {
  float x, y;
};
```

Arguments are forwarded, and no explicit constructor is required.
```cpp
entity.assign<Point>(1.0f, 2.0f);
```

The downside to this is that only non-narrowing conversions are allowed. So if those floats were replaced by doubles or 32 bit ints you'd get an error.
```cpp
entity.assign<Point>(1, 2); // narrowing error
entity.assign<Point>(1.0, 2.0); // narrowing error
```

**Comment by alecthomas** [comment]
This is an interesting idea, but I think the lack of backwards compatibility due to the narrowing errors would be an issue. For example, trying this with just EntityX breaks many unit tests.

It might be good to implement this in EntityX 2.0 though.

**Comment by notlion** [comment]
Agreed that it would almost certainly break a lot of code in a way that's not very obvious. That's why I held off from making a pull request. Still, it would be nice to not have to write all that constructor boilerplate.

**Comment by alecthomas** [comment]
I don't think I will implement this.
