### ISSUE TITLE
Trivially copyable Entity

### ISSUE THREAD

**Issue by tahsmith** [alecthomas/entityx#88]
Entity class as has a user defined copy-constructor and copy-assign operator both of which would be equivalent to the compiler generated ones. Removing them would make Entity trivially copyable, which helps, among other things, delegate classes like std::function which copy lambdas. (A delegate class I use only allows lambdas if they are small and trivially copyable)

Is there any reason that Entity has the user defined copy-constructor and copy-assign operator? I've tested removing them on VS2013 and it works and shows Entity as trivially copyable via the is_trivially_copyable type trait

**Comment by alecthomas** [comment]
No reason that I can recall. I might have had some checks in there at some time, since removed. PR welcome!

**Comment by tahsmith** [comment]
Done!

**Comment by alecthomas** [comment]
Fixed in #89, thanks!
