### ISSUE TITLE
Scheduling events

### ISSUE THREAD

**Issue by omikun** [alecthomas/entityx#91]
Would it be possible to schedule events for the future? This would be really useful for periodic events without checking every entity at every frame.

**Comment by alecthomas** [comment]
I think this is out of scope for EntityX. It should be simple (enough) to write a System that handles this yourself.

**Comment by omikun** [comment]
Is there a way to write a system that can subscribe to all events in general? Or would I have to manually subscribe to every event type I want to be schedulable?

**Comment by alecthomas** [comment]
That should not be the case. Here's how you subscribe to two events:

```c++
  em.subscribe<Explosion>(system);
  em.subscribe<Collision>(system);
```

It's not possible to subscribe to all events, as there's no way to statically differentiate between them.
