### ISSUE TITLE
Double delete of entities does not trigger an assert

### ISSUE THREAD

**Issue by omikun** [alecthomas/entityx#92]
Hello, I am using the latest version of entityx (amazing library btw!) and I am running into the problem where after destroying a couple of entities and then creating others, I run into the problem where the newly created entities already have components assigned, and any assignment on top of this results in an assertion error regarding the component family mask of the entity.

**Comment by alecthomas** [comment]
Which version are you using? You mean master, or one of the branches?

If you can build and run the tests, there are several that should fail if this is the case. You can do this with:

```
mkdir build && cmake -DENTITYX_BUILD_TESTING=1 -DCMAKE_BUILD_TYPE=Debug .. && make && make test
```

Also, can you show me some sample code to replicate this?

**Comment by alecthomas** [comment]
I've just added another test for this, and can't replicate it.

**Comment by omikun** [comment]
Thanks, I found out I was silently deleting entities twice, and occasionally would get an error when creating an entity afterwards. Fixing the double deletion fixed it.

**Comment by alecthomas** [comment]
Excellent, though it's surprising it doesn't assert when that occurs. That actually seems like a bug that an assert should catch.

**Comment by alecthomas** [comment]
Did you compile EntityX with RelWithDebInfo or Debug? If so it should assert on double delete already. Basically, I can't replicate the issue...
