### ISSUE TITLE
Components pulled from const entities are invalid

### ISSUE THREAD

**Issue by notlion** [alecthomas/entityx#95]
I noticed this when updating my code from 9e4314ef1d4575caa99fee3a4ae7f479b8153a34. When `entity.component()` is called on a const Entity it looks like a new template instantiation is being created for the const version of the component. This causes the function to return an invalid ComponentHandle. I'm assuming this is a bug and not by design, since I expect you'd just want to return a `const ComponentHandle<Component>` in this case, not a `ComponentHandle<const Component>`.

I wrote a test to make sure this wasn't just happening in my own app:

```cpp
TEST_CASE_METHOD(EntityManagerFixture, "TestConstComponentsNotInstantiatedTwice") {
  Entity a = em.create();
  a.assign<Position>(1, 2);

  const Entity b = a;

  REQUIRE(a.component<Position>().valid());
  REQUIRE(b.component<Position>().valid());
}
```

**Comment by alecthomas** [comment]
This is quite tricky. On the one hand, you could argue that this is correct behaviour because the non-const `Position` is not valid on `b` where `const Position` should be. On the other hand, it's very confusing.

Either way, the following still doesn't work, which is definitely a bug:

```c++
REQUIRE(b.component<const Position>().valid());
```

**Comment by alecthomas** [comment]
That was a lot more painful than I would have hoped. If you that branch a try I'd appreciate it.

**Comment by notlion** [comment]
Thanks for looking into this, and for the fix. It does indeed make `component<const Position>()` return a valid ComponentHandle, but it's a handle to a Component with a different family id that hasn't been assigned to the Entity. Trying to get data out of it with the -> operator will result in a segfault.

If I add this line the test fails:
```cpp
REQUIRE(Component<Position>::family() == Component<const Position>::family());
```

And this will fail via segfault:
```cpp
auto x = b.component<const Position>()->x;
```

**Comment by alecthomas** [comment]
Are you sure you're using the right branch? On that branch The test you
originally wrote passes on clang, gcc and MSVC 2015 with latest CTP.

Additionally you should get a compiler error when trying to retrieve
non-const components from a const Entity (I tested this manually).

**Comment by alecthomas** [comment]
Sorry, passes if you use a const component.

**Comment by notlion** [comment]
Yup I double-checked that I was on the correct branch. I tested with cc3a2fa as well as a1dfd15. The original test that I wrote does pass, but the use case in my app fails when it tries to retrieve data from the component (since it's trying to pull from a different pool).

**Comment by notlion** [comment]
Sorry. There was a mistake with the example I gave above. The test that assigns `component<const Position>()->x` to x will be elided by the compiler and the test will actually pass. If you do something like this the segfault should happen:
```cpp
std::cout << b.component<const Position>()->x << std::endl;
```

**Comment by alecthomas** [comment]
Okay, try bbb47d10f715ad8847795354ebf8e045e89979d7 on the fix_issue_95 branch. I added remove_const to all component family lookups, so hopefully it should work now.

**Comment by notlion** [comment]
Awesome. This works with my code, and all the tests pass. Thanks for the fix!
