### ISSUE TITLE
#include <functional>

### ISSUE THREAD

**Issue by waldnercharles** [alecthomas/entityx#97]
In the [experimental/compile_time](https://github.com/alecthomas/entityx/tree/experimental/compile_time) branch, while compiling on windows under visual studio, an error is thrown regarding std::function not being found.

`#include <functional>` in entityx.hh fixes the issue for me. It's a standard library and so I don't believe it should cause any issue with a *nix build. Correct me if I'm wrong.

**Comment by alecthomas** [comment]
Thanks!

**Comment by alecthomas** [comment]
Nice, fixed the AppVeyor [build](https://ci.appveyor.com/project/alecthomas/entityx). Thanks again.
