### ISSUE TITLE
maybe add System update priority fields

### ISSUE THREAD

**Issue by roig** [alecthomas/entityx#98]
I think that the Systems should have a priority variable (int for example). Then the SystemManager can order the updates of the systems based on that variable. By default, if no priority has set for the system, set the priority to 0.

I think that the SystemManager class should have something like as a private variable:
```
//Key is the priority
std::ordered_map<int , std::vector<std::shared_ptr<BaseSystem> > > m_systems_priority;
```
So when a System is inserted it will populate vector in that map in the priority (key) of that system.

Then the function:
```
void update_all(TimeDelta dt);
```
Should iterate  m_systems_priority map based on priority to do the updates of the systems in order.

Why? Because I think we can't add a custom system dinamically and set the update order accordingly when the application is running.

Thoughts?
Thank you for that library :+1:

**Comment by alecthomas** [comment]
The System stuff is deliberately very simple, but it's trivial to roll your own. This seems like a bit of an edge case, so I'd suggest the latter if you really need it.
